// Generated by https://quicktype.io

export interface ResumeResponse {
  data: Resume;
}

export interface Resume {
  id: number;
  file: string;
  userId: number;
  filePath: string;
  updatedAt: string;
}
